### PR TITLE
fix: improve warnings for Direct Path xDS set via env

### LINKED ISSUE #2427: DirectPath Misconfiguration emitted for non-DirectPath client instances in a DirectPath enabled client application
#### Environment details
1. GCE
2. gax 2.41.0
3. GOOGLE_CLOUD_ENABLE_DIRECT_PATH_XDS is set

#### Details
In https://github.com/googleapis/sdk-platform-java/pull/2105 we added warning logs for DirectPath misconfiguration. The logic is that we first check if DirectPath xDS is enabled, then check if DirectPath is enabled. This could cause misleading warning logs in the case where non-DirectPath client instances in a DirectPath enabled client application. For example: a customer's application may contains a GCS client and a Bigquery client. The customer use setAttemptDirectPath to enable DirectPath in its GCS client, and set GOOGLE_CLOUD_ENABLE_DIRECT_PATH_XDS to enable DirectPath xDS. In this case, this [warning log](https://github.com/googleapis/sdk-platform-java/blob/main/gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java#L276-L282) will be printed in the customer's Bigquery client.

### PR DESCRIPTION
**Pull request by diegomarquezp**
Fixes #2427

### Context
If `GOOGLE_CLOUD_ENABLE_DIRECT_PATH_XDS` is set in the environment aiming to enable Direct Path xDS in another client, we want to just warn the user that _if this is intended_, it can be a misconfiguration and that the gRPCLB Direct Path setting should be enabled as well.

### Approach
As said in the context, we will _warn_ the user that it _could_ be a misconfiguration _if_ the env var setting was meant for the client in question. Other warn cases remain the same.

### Coverage
Due to the fact that part of the method in question is tested via a special env var test (not detected by SonarCloud), it will show as uncovered. See this screenshot for coverage of all tests combined
image

### CODE REVIEW

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 1]
```diff
@@ -273,32 +276,36 @@ private boolean isDirectPathEnabled() {
...
   // for a client.
   private void logDirectPathMisconfig() {
-    if (isDirectPathXdsEnabled()) {
-      // Case 1: does not enable DirectPath
-      if (!isDirectPathEnabled()) {
-        LOG.log(
-            Level.WARNING,
-            "DirectPath is misconfigured. Please set the attemptDirectPath option along with the"
-                + " attemptDirectPathXds option.");
+    final String onlyOneDirectPathEnabledMessage =
```
Comment (mohanli-ml) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:302]: The name onlyOneDirectPathEnabledMessage is confusing. The history is like this:
1. Originally DirectPath infra is based on gRPCLB, which is controlled by attemptDirectPath option;
2. Later a new DirectPath infra based on xDS/Traffic Director is developed, thus we add attemptDirectPathXds option and DIRECT_PATH_ENV_ENABLE_XDS env. However, we require that the attemptDirectPath must also be set, otherwise attemptDirectPathXds/DIRECT_PATH_ENV_ENABLE_XDS will be ignored.
3. We are in the process of deprecating gRPCLB, and only xDS/TD will be supported in the future.

So one DirectPath is a bit misleading because users can only use either gRPCLB or TD.

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 2]
```diff
@@ -273,32 +276,36 @@ private boolean isDirectPathEnabled() {
...
+        "DirectPath is misconfigured. Please set both the "
+            + "attemptDirectPath and the attemptDirectPathXds options.";
+    if (isDirectPathEnabled()) {
+      // Case 1: does not enable DirectPath xDS
```
Comment (mohanli-ml) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:306]: The order of the two IF here should not be changed. We do not care the case where DirectPath is enabled while DirectPathXds is not enabled (which means customers are trying to use gRPCLB, no matter on intent or by mistake), because new customers can only use xDS/TD. Thus, we only care about users trying to use xDS/TD, but they forget to set the attemptDirectPath option.

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 1 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java]: Thank you for the explanation. I removed this variable because the suggestion in https://github.com/googleapis/sdk-platform-java/pull/3019#discussion_r1671030813 would make it unnecessary.

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 2 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java]: Makes sense. I adjusted it as indicated:
 - xDS set via env -> no TD set -> warn that this _could_ be unintended
 - xDS set via builder -> no TD set -> warn as usual
 - TD set -> no xDS set -> no warning

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 3]
```diff
@@ -273,42 +276,57 @@ private boolean isDirectPathEnabled() {
...
+  private boolean isDirectPathXdsEnabledViaEnv() {
+    String directPathXdsEnv = envProvider.getenv(DIRECT_PATH_ENV_ENABLE_XDS);
+    return Boolean.parseBoolean(directPathXdsEnv);
+  }
+
   @InternalApi
   public boolean isDirectPathXdsEnabled() {
     // Method 1: Enable DirectPath xDS by option.
-    if (Boolean.TRUE.equals(attemptDirectPathXds)) {
+    if (isDirectPathXdsEnabledViaBuilderOption()) {
```
Comment (mohanli-ml) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:291]: You can just return isDirectPathXdsEnabledViaBuilderOption() || isDirectPathXdsEnabledViaEnv().

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 4]
```diff
@@ -273,42 +276,57 @@ private boolean isDirectPathEnabled() {
...
   // for a client.
   private void logDirectPathMisconfig() {
     if (isDirectPathXdsEnabled()) {
-      // Case 1: does not enable DirectPath
-      if (!isDirectPathEnabled()) {
+      // Case 1: Direct Path is only enabled via XDS env var. We will _warn_ the user that this is a
+      // misconfig if they
+      // intended to set the env var.
+      if (!isDirectPathEnabled() && isDirectPathXdsEnabledViaEnv()) {
+        LOG.log(
```
Comment (mohanli-ml) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:307]: Make the case 1 and case 2 this way:
if (isDirectPathXdsEnabled()) {
  if (!isDirectPathEnabled() {
    // case 1: ...
    if (isDirectPathXdsEnabledViaEnv()) {...}
    // case 2: ...
    if (isDirectPathXdsEnabledViaEnv()) {...}
  } else {
    // case 3: ...
    // case 4: ...
  }
}

I think this will make the code more readable.

Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java]: Agreed, thank you. Modified accordingly.

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 3 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java]: Done.

**Review by mohanli-ml — APPROVED** [review]

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 5]
```diff
@@ -273,42 +276,54 @@ private boolean isDirectPathEnabled() {
...
-            "DirectPath is misconfigured. Please set the attemptDirectPath option along with the"
-                + " attemptDirectPathXds option.");
+        // Case 1: Direct Path is only enabled via XDS env var. We will _warn_ the user that this is
+        // a misconfiguration if they intended to set the env var.
+        if (isDirectPathXdsEnabledViaEnv()) {
+          LOG.log(
+              Level.WARNING,
+              "Env var "
+                  + DIRECT_PATH_ENV_ENABLE_XDS
+                  + " was found. If this is intended for "
```
[the remark this answers is not in the document]
Comment (lqiu96) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:306]: Wait, nvm I think I misunderstood.

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 6]
```diff
@@ -273,42 +276,54 @@ private boolean isDirectPathEnabled() {
...
+                  + "this client, please note that this is a misconfiguration and set the attemptDirectPath option as well.");
+        }
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:308]:
```suggestion
          LOG.log(
              Level.WARNING,
              "Env var "
                  + DIRECT_PATH_ENV_ENABLE_XDS
                  + " was found and set to TRUE, but DirectPath was not enabled for this client. If this is intended for "
                  + "this client, please note that this is a misconfiguration and set the attemptDirectPath option as well.");
        }
```

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 7]
```diff
@@ -273,42 +276,54 @@ private boolean isDirectPathEnabled() {
...
+        // Case 2: Direct Path TD must be set along with xDS. Here we warn the user about this.
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:309]: What is Direct Path TD?

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 8]
```diff
@@ -273,42 +276,54 @@ private boolean isDirectPathEnabled() {
...
+        else if (isDirectPathXdsEnabledViaBuilderOption()) {
+          LOG.log(
+              Level.WARNING,
+              "DirectPath is misconfigured. Please set the attemptDirectPath option along with the"
+                  + " attemptDirectPathXds option.");
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:314]:
```suggestion
              "DirectPath is misconfigured. The DirectPath XDS option was set, but the attemptDirectPath option was not. Please set the attemptDirectPath option along with the"
                  + " attemptDirectPathXds option.");
```

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 9]
```diff
@@ -273,42 +276,54 @@ private boolean isDirectPathEnabled() {
...
+        } else {
+        } // impossible - added this `else` for readability.
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:316]: nit/ personal opinion: I don't think you need to add the extra else block. I think you can just add a comment above about how there are only two possible cases for misconfigurations

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 7 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:309]: That's the direct path that falls back to gRPCLB (https://github.com/googleapis/sdk-platform-java/issues/2164)

Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:309]: I'm clarifying this in the comment

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 9 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java]: Makes sense. I removed the `else` and added a comment above

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 7 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java]: Done

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 10]
```diff
@@ -273,42 +276,55 @@ private boolean isDirectPathEnabled() {
...
     if (isDirectPathXdsEnabled()) {
-      // Case 1: does not enable DirectPath
       if (!isDirectPathEnabled()) {
-        LOG.log(
-            Level.WARNING,
-            "DirectPath is misconfigured. Please set the attemptDirectPath option along with the"
-                + " attemptDirectPathXds option.");
+        // Only two cases are possible: Direct path xDS enabled via env var or via builder.
+        // Case 1: Direct Path is only enabled via XDS env var. We will _warn_ the user that this is
+        // a misconfiguration if they intended to set the env var.
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:301]:
```suggestion
        // This misconfiguration occurs when Direct Path xDS is enabled, but Direct Path is not
        // Direct Path xDS can be enabled two ways: via environment variable or via builder.
        // Case 1: Direct Path is only enabled via xDS env var. We will _warn_ the user that this is
        // a misconfiguration if they intended to set the env var.
```

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 11]
```diff
@@ -273,42 +276,55 @@ private boolean isDirectPathEnabled() {
...
-      return true;
-    }
-    // Method 2: Enable DirectPath xDS by env.
-    String directPathXdsEnv = envProvider.getenv(DIRECT_PATH_ENV_ENABLE_XDS);
-    boolean isDirectPathXdsEnv = Boolean.parseBoolean(directPathXdsEnv);
-    if (isDirectPathXdsEnv) {
-      return true;
-    }
-    return false;
+    return isDirectPathXdsEnabledViaEnv() || isDirectPathXdsEnabledViaBuilderOption();
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:290]: nit: Can you add javadoc for this public method? It is marked as internal, but that unfortunately doesn't stop everyone from using it.

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java [hunk 12]
```diff
@@ -273,42 +276,55 @@ private boolean isDirectPathEnabled() {
...
+        if (isDirectPathXdsEnabledViaEnv()) {
+          LOG.log(
+              Level.WARNING,
+              "Env var "
+                  + DIRECT_PATH_ENV_ENABLE_XDS
+                  + " was found and set to TRUE, but DirectPath was not enabled for this client. If this is intended for "
+                  + "this client, please note that this is a misconfiguration and set the attemptDirectPath option as well.");
+        }
+        // Case 2: Direct Path xDS was enabled via Builder. Direct Path TD (via gRPCLB) must be set
+        // along with xDS.
```
Comment (lqiu96) [inline gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:311]:
```suggestion
        // Case 2: Direct Path xDS was enabled via Builder. Direct Path Traffic Director must be set (enabled with `setAttemptDirectPath(true)`) along with xDS.
```

Let me know if this the suggestion makes sense. I just took out the abbreviation TD -> Traffic Director and added that TD can be enabled with `setAttemptDirectPath(true)`

**Review by lqiu96 — APPROVED** [review]
LGTM, if you could address the last bit of comments. Thanks!

File: gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java (hunk 11 above)
Comment (diegomarquezp) [reply gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java:297]: Sure, added
